sudo: required
services:
  - docker
env:
  global:
    secure: "xdzV084P3DQA9PBWmrCGgysHQ2tb9OfL1W97bkjKDCAi99gcACYVLid2uUWZGbh99jsfeN4a7vOFCj8MFrm2tfbFGx1JF1WWIsLDkVY0MLdcZR79SnUiX2GYNYU7iNrbrD3XEiwPz88TTVkwX8X8BLijU7Csn/5SoodiGFfpukQkSP/1midpQL3bN0bp+16xRGwxjqxUT6O6me+ctB66P/PBzcqV0K50kpXHwT/94G1tBj7aXmiYMXFjlpAdjhMFiIqH7NhQ3U44kY6KTpl++zdhzWldSqjVCu1VndF+JDEjYkN21pH6s1RDiWMplZWfZgoKOpR5dAl56ajxOdOeOM8pnwAxhfZkxWSQpKIRFTHGXk0Be2FmgKmWBWMiYusx9bfiUs3icRdsKQXOlPXPRcDFvewxML50TjmisqCkWynjEsGuJ/XOsSGz/4DBu7tdDLrestJl7bAAFcn4Lzb/UIWuO5eygO10fV4cShGXyMAigC7qw779hdXpQ2lgIDSunfhI9EYMda9vh9fPWKyKXLFC5ta8J2+oS1VlApJzl5AzXmIRnNZUliPEwivuae9msth6sWWCqFHGXH2540nTnjARQAYqB1sshiSpVhOtz1OFZYScHcrBq3N2NXh1psavshhqOePl8AH+24S1c33YFtsfczzqczHO/fu7jCNjU00="

before_script:
  - docker pull sakson/sonar-scanner-nodejs || true
script:
  - docker build --pull --cache-from sakson/sonar-scanner-nodejs --tag sakson/sonar-scanner-nodejs .

before_deploy:
  - docker login -u "traviscisakson" -p $REGISTRY_PASS
deploy:
  provider: script
  script: docker push sakson/sonar-scanner-nodejs
  on:
    branch: master
