sudo: required
services:
  - docker
env:
  global:
    secure: zCEEXK99ZgedWx54fVP8e+a+vsUCKxAh60ZQlo1X1YbmZ1SXhCsMjbEMCG4+8MdH0ndBs7aejONhuCZhXMD+gQIm/t1KN3mdRcgZzG/KLHWT4WhlsusZfU0mIyhsLIQlBWqfSrt0H7OrV9ykFjSQRdtdgKshq7Jbh6eoZqW71tcAfpLNwo9CIlGOfEnljgw0FAplLcyJGgB0Ic8nF3fO5Jbpoj8X2a9MxJIUj0Elvj7iAch1mTJFG/dYtYTy3G1Sgg9mDK9PiTx/Zgtr+xJnT1n83Ols6rPUNSGROdso3622QO9Yb0ALV/23Jz7rhJQ5nkLoJi2HjNrD++efhIyXfv0shwtmtbwrYwIjJQgHykKVQMWwK4B3ZpzoQ0XSlhqoZXT/TmKZAGOfMZ588dupNkZhAtofDUxU0aMQxT2kiylRRS90L1AzEnkwwxaJ+wYysbHGwzH5Z+3lyIr38uKet0Rj7nDDUV1r8NnkFcBHeI38coKG2Mbma9Ee3wol5W8HjUf1h3dB7NjTsa517GHEAkHiYMfIJc4zebYZjTukjuLaVHrJsAKpZViuuJT74aGeLE7ShhpRhkbthml4FZ/Je/py9T35/4WVeuhOh2adaKxCe/3cNttNlaYD7wdTbRwhyt7i8+8VaSjOXLMIrvlKiQmUOukLzK9vO2qFR33SUaM=

before_script:
  - docker pull sakson/sonar-scanner-nodejs || true
script:
  - docker build --pull --cache-from sakson/sonar-scanner-nodejs --tag sakson/sonar-scanner-nodejs .

after_script:
  - docker images

before_deploy:
  - docker login -u "traviscisakson" --password-stdin "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push sakson/sonar-scanner-nodejs
  on:
    branch: master
