sudo: required
services:
  - docker
env:
  global:
    - secure: "y7udmWlcst0aYFfn6jus3ZcefLCXii/JnZZ2Zl5nluRGQgbUtb8BQkXA4168rMjr5PLuD2OGkihoozWYYACnv0AhYdDDqRvYD0LE3a0gAhiFquqw9yt35RldYt6Oq0FI9Vn8Z2dfVhIb1M/it+w3TN65mSreabEKa7TeC1582gO9/ReMQ7IZhsksB5sDm5X+If5h6fSgWTqn7a9Adt7ZPkcHo2MACHhQY5ZeGGL4PZ2Gw87pi1rsRoC6ykxj48/Yf2bP5t+O9Wu6uQEuCK2liljjCqOPvt0aa0Ffm9f4gINx1EJ18P0zsSfyrzxkcVq4iHmAlwqGuXCBwJj0oly6Oh40Rgeo6tFpNs8vezZMOZomA5smEIexHsejnfA1P3PAfy/GrQLZJVzBt7E0KgxHNPbgsjsPgz9HIbu5IeiW3MLOSvxK08mzGGBavUcU7GFENxJyJQemnN01NAxXxY8TgwCbBYm08pMvz0pqKb/f7X3ltLWbG4jxloIC5DX5LgBc93+REMemwsLzA7Z+OAUvrgVrmWOFgQdrIfrStbaB7FmAFAGxc7qMhweWsCE4sp7DZnAh+9WCRbPvomSLRdSgVYQax4s40AAzydy8e8jdheZqs64Je6NAGhwIChaPtkvbu4rXVEOQtvFRrEI78raET8skKTbU5yaOZUjeZSGfpIc="
    - REGISTRY_USER=traviscisakson


before_script:
  - docker pull sakson/sonar-scanner-nodejs || true
script:
  - docker build --pull --cache-from sakson/sonar-scanner-nodejs --tag sakson/sonar-scanner-nodejs .

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" --password-stdin -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push sakson/sonar-scanner-nodejs
  on:
    branch: master
